"""add scenario on_sale

Revision ID: 360f036d2731
Revises: b9239a8602ae
Create Date: 2026-08-10 19:09:12.972249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360f036d2731'
down_revision: Union[str, Sequence[str], None] = 'b9239a8602ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('on_sale', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'on_sale')
    # ### end Alembic commands ###
