"""add notifications table

Revision ID: 58f71c3926e5
Revises: 53f0702dbf0f
Create Date: 2026-08-07 10:51:42.507107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f71c3926e5'
down_revision: Union[str, Sequence[str], None] = '53f0702dbf0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('report', 'payment', 'system', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('user_id', 'type', 'payload_hash', name='uq_notification_event')
    )
    op.create_index(op.f('ix_notifications_payload_hash'), 'notifications', ['payload_hash'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_payload_hash'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS notification_type')
