"""add scenario owner_id

Revision ID: 6a5e73674b6a
Revises: 6c8e2dfd61ee
Create Date: 2026-08-11 18:38:16.328751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5e73674b6a'
down_revision: Union[str, Sequence[str], None] = '6c8e2dfd61ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_scenarios_owner_id'), 'scenarios', ['owner_id'], unique=False)
    op.create_foreign_key(op.f('fk_scenarios_owner_id_users'), 'scenarios', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_scenarios_owner_id_users'), 'scenarios', type_='foreignkey')
    op.drop_index(op.f('ix_scenarios_owner_id'), table_name='scenarios')
    op.drop_column('scenarios', 'owner_id')
    # ### end Alembic commands ###
